### ISSUE TITLE
Returning error ONLY when ETH is in offer

### ISSUE THREAD

**Issue by pullidea-dev** [ProjectOpenSea/seaport-js#151]
Reading seaport doc, ETH can be in offer, but in implementation returns error every time.
Here is the `swapParameters`
```
"swapParameters": {
    "offerer": "0xD15E4CCD70aBB2465Cc38DB64945A8cdA6496E96",
    "zone": "0x0000000000000000000000000000000000000000",
    "zoneHash": "0x3000000000000000000000000000000000000000000000000000000000000000",
    "startTime": "1672853035",
    "endTime": "115792089237316195423570985008687907853269984665640564039457584007913129639935",
    "orderType": 0,
    "offer": [
      {
        "itemType": 2,
        "token": "0x7b9fd44513ef3a714614094963c6dc4cdfcc40cb",
        "identifierOrCriteria": "4",
        "startAmount": "1",
        "endAmount": "1"
      },
      {
        "itemType": 0,
        "token": "0x0000000000000000000000000000000000000000",
        "identifierOrCriteria": "0",
        "startAmount": "150000000000000",
        "endAmount": "150000000000000"
      }
    ],
    "consideration": [
      {
        "itemType": 2,
        "token": "0x7b9fd44513ef3a714614094963c6dc4cdfcc40cb",
        "identifierOrCriteria": "5",
        "startAmount": "1",
        "endAmount": "1",
        "recipient": "0xD15E4CCD70aBB2465Cc38DB64945A8cdA6496E96"
      }
    ],
    "totalOriginalConsiderationItems": 1,
    "salt": "0x00000000fc860db0b2df7719",
    "conduitKey": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "counter": 0
  },
```
And error message:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x0f79395687E1Ff0156D9fA00a7B55Dc0B88ddF96","to":"0x00000000006c3852cbEf3e08E8dF289169EdE581","data":"0xb3a34c4c00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000003e0000000000000000000000000d15e4ccd70abb2465cc38db64945a8cda6496e960000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000002c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000063b5b62bffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff3000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000fc860db0b2df771900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000020000000000000000000000007b9fd44513ef3a714614094963c6dc4cdfcc40cb0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000886c98b760000000000000000000000000000000000000000000000000000000886c98b76000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000007b9fd44513ef3a714614094963c6dc4cdfcc40cb000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000d15e4ccd70abb2465cc38db64945a8cda6496e96000000000000000000000000000000000000000000000000000000000000004037f5d6ba9284a8b8b3afa8b37d44fc98da6ae358962fcd24625535584ab438fb8fcf984f1f89356fc7c0b7ec4765f1f4d2b166ae8688da0caca1d9de503ff733c5d24601","accessList":null}, error={"code":-32603,"message":"execution reverted","data":{"originalError":{"code":3,"data":"0x12d3f5a3","message":"execution reverted"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.1)
    at Logger.makeError (index.js:275:1)
    at Logger.throwError (index.js:285:1)
    at checkError (json-rpc-provider.js:118:1)
    at Web3Provider.<anonymous> (json-rpc-provider.js:737:1)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.js:21:1)
```
I am using default metamask provider.
And weird thing is I am seeing error ONLY when ETH is in offer, ETH + ERC also not working.
But when I add ETH in consideration, it works.

Any explanation on this?

**Comment by cody-evaluate** [comment]
having the same issue

**Comment by ryanio** [comment]
ETH can't be in the offer because ETH cannot be programmatically taken out of an account, only WETH can. It can be a consideration item because ETH can be sent in the fulfillment transaction. Hope that helps explain.
